package hslu.fs17.mobpro.project.activitytracker.model;


import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Keep;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.annotation.Generated;

@Entity
public class Author {
    @Id
    long id;

    private String name;
    private String familyname;
    private String email;

    public Author(final String name, final String familyname) {
        this.name = name;
        this.familyname = familyname;
    }


    @Generated(443330475)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Author(long id, String name, String familyname, String email) {
        this.id = id;
        this.name = name;
        this.familyname = familyname;
        this.email = email;
    }


    @Generated(64241762)
    public Author() {
    }


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFamilyname() {
        return familyname;
    }

    public void setFamilyname(String familyname) {
        this.familyname = familyname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getWholeName() {
        return this.familyname + " " + this.name;
    }
}
