package hslu.fs17.mobpro.project.activitytracker.model;


import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Keep;
import io.objectbox.annotation.apihint.Internal;

@Entity
public class Author {
    @Id
    long id;

    private String name;
    private String lastname;
    private String email;

    public Author(final String name, final String familyname) {
        this.name = name;
        this.lastname = familyname;
    }


    @Keep
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Author(long id, String name, String lastname, String email) {
        this.id = id;
        this.name = name;
        this.lastname = lastname;
        this.email = email;
    }


    @Keep
    public Author() {
    }


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getWholeName() {
        return this.lastname + this.name;
    }
}
